openapi: 3.1.0
info:
  version: 1.0.0
  title: Data Transfer Exchange UC1 
  contact:
    name: Contact our support
    email: Ariane@example.com #Ariane
  license:
    name: The MIT License (MIT)
    url: 'https://opensource.org/licenses/MIT'
  x-logo:
    url: './paths/DALLE-Logo.webp'
    altText: OpenAPI example logo

  description: 
    "This is an online documentation for the data exchange format of the DRK-UC1 project.
    
    !!Work in progress!! This documentation is still under construction and will be updated regularly."
security:
  - apiKey: [] 
x-tagGroups:
  - name: General
    tags:
      - Event
      - TouristAttraction
      - Organization
      - Location
      - Person
      - CreativeWork

  - name: MediaObjects
    tags:  
      - TextObject
      - ImageObject
      - VideoObject
      - AudioObject

  - name: External Resources  
    tags:  
      - Article
      - DDB-Object

  - name: TouristObjects
    tags:  
      - TouristDestination  

  - name: Nutzungsverhalten
    tags:     
      - Account
      - VendorProfile
      - CustomerProfile
      - Review
 
servers:
  - url: https://api.uc1-example.com/v1


  
paths:
  /accounts:
    get:
      tags:
        - Account
      summary: Provides public information about accounts
      description: "TODO: Write description"
      operationId: getAccounts
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "./components/schemas/Account.yaml"
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
  /events:
    get:
      tags:
        - Event
      summary: Provides public information about events
      description: "TODO: Write description"
      operationId: getEvents
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/Event.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
  /organizations:
    get:
      tags:
        - Organization
      summary: Provides public information about organizations
      description: "TODO: Write description"
      operationId: getOrganizations
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/Organization.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
  
  /locations:
    get:
      tags:
        - Location
      summary: Provides public information about locations
      description: "TODO: Write description"
      operationId: getLocations
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/Location.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
  
  /tourist-attractions:
    get: 
      tags:
        - TouristAttraction
      summary: Provides public information about tourist attractions
      description: "TODO: Write description"
      operationId: getTouristAttractions
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/TouristAttraction.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
      
  /tourist-destinations:
    get:
      tags:
        - TouristDestination
      summary: Provides public information about tourist destinations
      description: "TODO: Write description"
      operationId: getTouristDestinations
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/TouristDestination.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
  /images:
    get:
      tags:
        - ImageObject
      summary: Provides public information about images
      description: "TODO: Write description"
      operationId: getImages
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/ImageObject.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
          

  /videos:
    get:
      tags:
        - VideoObject
      summary: Provides public information about videos
      description: "TODO: Write description"
      operationId: getVideos
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/VideoObject.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
        
        
  /audios:
    get:
      tags:
        - AudioObject
      summary: Provides public information about audios
      description: "TODO: Write description"
      operationId: getAudios
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/AudioObject.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
          
  
  /texts:
    get:
      tags:
        - TextObject
      summary: Provides public information about texts
      description: "TODO: Write description"
      operationId: getTexts
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/TextObject.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value

  /articles:
    get:
      tags:
        - Article
      summary: Provides public information about articles
      description: "TODO: Write description"
      operationId: getArticles
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/Article.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
          
  /creative-works:
    get:
      tags:
        - CreativeWork
      summary: Provides public information about creative works
      description: "TODO: Write description"
      operationId: getCreativeWorks
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/CreativeWork.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
        
  /reviews:
    get:
      tags:
        - Review
      summary: Provides public information about reviews
      description: "TODO: Write description"
      operationId: getReviews
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/Review.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
  
  /vendors:
    get:
      tags:
        - VendorProfile
      summary: Provides public information about vendors
      description: "TODO: Write description"
      operationId: getVendors
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/VendorProfile.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
  
  /customers:
    get:
      tags:
        - CustomerProfile
      summary: Provides public information about customers
      description: "TODO: Write description"
      operationId: getCustomers
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/ExampleObject.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value
      
  /ddb-objects:
    get:
      tags:
        - DDB-Object
      summary: Provides public information about DD-Objects
      description: "TODO: Write description"
      operationId: getDDBObjects
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/schemas/DDBObject.yaml
              #example:
              #  $ref: "./components/examples/Account.json"
        "400":
          description: Invalid status value




    
   